gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    single_use: true
    cookie:
        enabled: true
        path: /site_de_musique/api/public/api
        secure: true
        same_site: none
    logout_firewall: main
