nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin:
            - '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Authorization']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/': ~
